# Generated by Django 4.0.2 on 2022-03-17 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0007_product_status_alter_product_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='portfolio/images/'),
        ),
    ]
