# Generated by Django 4.0.2 on 2022-03-04 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cod_product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default='patito', max_length=30, verbose_name='marca'),
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(default='pollito', max_length=150, verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='product',
            name='create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
    ]
